spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
  datasource:
    url: jdbc:postgresql://localhost:15432/wallet
    username: postgres
    password: postgres
